# Generated by Django 5.0.7 on 2024-10-13 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerApp', '0003_alter_planner_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planner',
            name='no_experience',
            field=models.IntegerField(default=0),
        ),
    ]
