# Generated by Django 5.0.7 on 2024-10-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannedProjectApp', '0002_plannedproject_cost_plannedproject_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedproject',
            name='planned_date',
        ),
    ]
