# Generated by Django 5.0.7 on 2024-10-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_remove_user_username_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
