# Generated by Django 5.0.7 on 2024-10-28 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plannedProjectApp', '0003_remove_plannedproject_planned_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funded_projects', to=settings.AUTH_USER_MODEL)),
                ('funded_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funded_projects', to='plannedProjectApp.plannedproject')),
            ],
            options={
                'unique_together': {('created_by', 'funded_project')},
            },
        ),
    ]
