# Generated by Django 5.0.7 on 2024-10-28 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funded_project_app', '0001_initial'),
        ('stakeholderApp', '0003_alter_stakeholder_monthly_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundedproject',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funded_projects', to='stakeholderApp.stakeholder'),
        ),
    ]
