# Generated by Django 5.0.7 on 2024-10-13 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholderApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='phone',
        ),
    ]
