# Generated by Django 5.0.7 on 2024-10-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholderApp', '0002_remove_stakeholder_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
