# Generated by Django 5.0.7 on 2024-10-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_rename_name_project_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('un_planned', 'Un Planned'), ('planned', 'Planned'), ('funded', 'Funded'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='un_planned', max_length=20),
        ),
    ]
