# Generated by Django 5.0.7 on 2024-10-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('project_owner', 'Project Owner'), ('local_leader', 'Local Leader'), ('planner', 'Planner'), ('engineer', 'Engineer'), ('stakeholder', 'Stakeholder'), ('rdb_official', 'RDB Official')], max_length=20),
        ),
    ]
