# Generated by Django 5.0.7 on 2024-10-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('project_owner', 'Project Owner'), ('planner', 'Planner'), ('engineer', 'Engineer'), ('stakeholder', 'Stakeholder'), ('rdb_official', 'RDB Official')], max_length=20),
        ),
    ]
